import { Platform, StyleSheet } from 'react-native';

export const Styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },

  flex_2: {
    flex: 2,
  },
  flex_1: {
    flex: 1,
    paddingTop: 0,
  },
  ScreenLayout: {
    flex: 1,
    flexDirection: 'column',
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  linearGradient: {
    height: '14%',
    paddingBottom: 20,
    borderColor: '#ffffff3d',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor:
      'radial-gradient(189.13% 141.42% at 0% 0%, rgba(255, 255, 255, 0.06) 0%, rgba(255, 255, 255, 0.10) 50%, rgba(0, 0, 0, 0.10) 100%)',
    boxShadow: 'rgba(255, 255, 255, 0.12) inset -1px 0px 5px 1px',
    padding: 16,
    width: '90%',
    gap: 3,
  },
  other: {
    padding: 20,
  },
  card_container: {
    flexDirection: 'row',
    borderRadius: 50,
    borderBlockColor: 'rgba(255,255,255,0.15)',
    backgroundColor: '#0606062c',
    padding: 10,
    alignItems: 'center',
    textAlign: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#00BFFF',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
  },
  hellowText: {
    fontSize: 50,
    color: 'white',
    width: '100%',
    fontFamily: 'NotoSans-Regular',
    textAlign: 'center',
    alignItems: 'center',
    alignContent: 'center',
    textTransform: 'lowercase',
  },
  unizyText: {
    fontFamily: 'MonumentExtended-Regular',
    fontSize: 24,
    color: 'white',
    fontWeight: '400',
    fontStyle: 'normal',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    width:'100%',
    textAlign:'center',
    zIndex:0,
    bottom: 10
    
  },
  selectlangvageCard: {
    borderRadius: 20,
    backgroundColor: 'blue',
    width: '100%',
    padding: 20,
    marginEnd: 10,
    marginStart: 10,
    margin: 10,
    shadowColor: '#c74242ff',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 3 },
    borderColor: 'rgba(255,255,255,0.15)',
    shadowOpacity: 0.2,
    overflow: 'hidden',
  },
  choselangeuageText: {
    color: '#ffffffff',
    fontWeight: 'bold',
    fontSize: 18,
  },
  langIcon_nextIcon: {
    width: 10,
    height: 10,
    padding: 10,
    margin: 2,
    borderBlockColor: '#000000',
    paddingRight: 10,
  },
  termsandConditionText: {
    color: '#ffffffff',
    fontWeight: '600',
    fontSize: 9,
    marginTop: 12,
  },
  selectlanguageText: {
    flex: 1,
    color: 'rgba(255, 255, 255, 0.72)',
    fontFamily: 'Urbanist-Medium',
    fontWeight: '500',
    paddingLeft: 10,
    fontSize: 17,
    lineHeight: 19.2,
  },

  SelectLanguageContainer: {
    flexDirection: 'row',
    padding: 12,

    alignItems: 'center',
    textAlign: 'center',
    borderWidth: 1,
    borderColor: '#FFFFFF3d',
    borderRadius: 40,
    // backgroundColor:
    //   'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 2px 8px 0 rgba(0, 0, 0, 0.25)',
    
  },

  //   Login
  // flex_1: {
  //     width: '100%',
  //     height: '100%',
  //     alignItems: 'center',
  //     flex: 1,

  //   },
  autoHeight: {
    height: 'auto', // lets content decide height
  },
  fullScreenContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginVertical: 20,
    padding: 16,
    flexShrink: 0,
    flexDirection: 'row',
    paddingTop: 50,
    opacity: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,

    // backgroundColor: '#000000',
  },
 cardView: {
 

    paddingTop: 15,
    padding: 10,
    marginTop: 0,
    borderWidth: 0.2,
    gap: 3,
    borderColor: '#ffffff3d',
    borderRadius: 16,
    backgroundColor:
      'radial-gradient(189.13% 141.42% at 0% 0%, rgba(255, 255, 255, 0.06) 0%, rgba(255, 255, 255, 0.10) 50%, rgba(0, 0, 0, 0.10) 100%)',
    boxShadow: '0 2px 8px 0 rgba(0, 0, 0, 0.09)',
    overflow: 'hidden',
    // backgroundColor: '#fff'
  },
  backIconRow: {
     padding: 12,
    borderRadius: 40,
    backgroundColor:
      'radial-gradient(189.13% 141.42% at 0% 0%, rgba(255, 255, 255, 0.06) 0%, rgba(255, 255, 255, 0.10) 50%, rgba(0, 0, 0, 0.10) 100%)',
    boxShadow: 'rgba(255, 255, 255, 0.12) inset -1px 0px 5px 1px',
    borderWidth: 0.4,
    borderColor: '#ffffff2c',
    height: 48,
    width: 48,
    position: 'absolute',
    top: -20,
    left: 0,
    right: 0,

    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },

  backIconRowEmpty: {
    display: 'flex',
    padding: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 40,

    borderWidth: 0.4,
    borderColor: '#ffffff2c',
    height: 48,
    width: 48,
  },

  emptyView: {
    display: 'flex',
    padding: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 40,
    opacity: 0.01,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 2px 8px 0 rgba(0, 0, 0, 0.25)',
  },
  //   container: {
  //     display: 'flex',
  //     width: '90%',
  //     padding: 16,
  //     flexDirection: 'column',
  //     alignItems: 'center',
  //     gap: 16,
  //     borderRadius: 12,
  //     backgroundColor: 'rgba(255, 255, 255, 0.06)',
  //     opacity: 0.9,
  //     overflow: 'hidden',
  //     borderColor: 'rgba(255, 255, 255, 0.3)',
  //     margin: 20,
  //   },
  login_container: {
    display: 'flex',
    width: '100%',
    height: 40,
    gap: 10,
    alignSelf: 'stretch',
    borderRadius: 12,
    borderWidth: 0.6,
    borderColor: '#ffffff2c',
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 1.761px 6.897px 0 rgba(0, 0, 0, 0.25)',
  },
  personalEmailID_TextInput: {
    width: '93%',
    fontFamily: 'Urbanist-Regular',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 22,
    fontStyle: 'normal',
    color:"#fff"
    
  },
  password_container: {
    display: 'flex',
    width: '100%',
    height: 40,
    alignSelf: 'stretch',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 1.761px 6.897px 0 rgba(0, 0, 0, 0.25)',

    borderWidth: 0.6,
    borderColor: '#ffffff2c',
    marginTop: 12,
  },
  password_TextInput: {
    width: '88%',
    paddingLeft: 4,
    fontFamily: 'Urbanist-Regular',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 22,
    color:'#fff'
  },
  forgetPasswordText: {
    color: 'rgba(255, 255, 255, 0.48)',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    fontWeight: 400,
    width: '100%',
    textAlign: 'right',
    marginTop: 10,
  },
    loginButton2: {
    display: 'flex',
    width: '100%',
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    //gap: 4,
    borderRadius: 100,
    //paddingTop: 6,
    paddingVertical: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.56)',
    marginTop: 6,
    borderWidth: 0.5,
    borderColor: '#ffffff2c',
  },
  loginButton: {
    display: 'flex',
    width: '100%',
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    //gap: 4,
    borderRadius: 100,
    //paddingTop: 6,
    paddingVertical: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.56)',
    marginTop: 10,
    borderWidth: 0.5,
    borderColor: '#ffffff2c',
  },
  loginText: {
    color: '#002050',
    textAlign: 'center',
    fontFamily: 'Urbanist-Medium',
    fontSize: 17,
    fontWeight: 500,
    letterSpacing: 1,
    width: '100%',
  },
  dontHaveAccountText: {
    color: 'rgba(255, 255, 255, 0.48)',
    textAlign: 'center',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 19,
  },
  signupText: {
    color: '#FFFFFF7A',
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 19,
    textDecorationStyle: 'solid',
    marginTop: 10,
    opacity: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },
  teamsandConditionText: {
    color: '#FFFFFF7A',
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 14,
    marginLeft: 5,
    fontWeight: '600',
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    opacity: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },
  teamsandConditionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },

  teamandCondition: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 1,
    paddingBottom: 30,
  },

  bycountuningAgreementText: {
    color: 'rgba(255, 255, 255, 0.48)',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    fontWeight: 400,
  },

  privacyPolicyText: {
    color: '#FFFFFF7A',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 'bold',
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
  },

  editText: {
    display: 'flex',
    width: '100%',
    height: 44,
    padding: 12,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 10,
    alignSelf: 'stretch',
    borderRadius: 12,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 1.761px 6.897px 0 rgba(0, 0, 0, 0.25)',
    fontSize: 17,
    fontFamily: 'Urbanist-Medium',
    fontWeight: '400',
    lineHeight: 22,
  },
  unizy_Text: {
    fontFamily: 'Monument Extended',
    top: 30,
    fontStyle: 'normal',
    lineHeight: 28.8,
    fontSize: 30,
    color: '#FFFFFF',
    fontWeight: '400',
    width: '100%',
    textAlign: 'center',
  },
  eyeIcon: {
    width: 24,
    height: 24,
    resizeMode:'contain'
    // paddingRight: 16,
  },
  eyeCross: {
    width: 24,
    height: 24,
    resizeMode:'contain'
  },
  donthaveAccountText: {
    color: 'rgba(255, 255, 255, 0.48)',
    textAlign: 'center',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 19,
    marginTop: 5,
  },
  topHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignContent: 'center',
    
  },

  NewtopHeader: {
    // flexDirection: 'row',
    // alignItems: 'center',
    // justifyContent: 'space-between',
    // alignContent: 'center',
    // paddingHorizontal: 16,
    display: 'flex',
     flexDirection: 'row',
    // alignItems: 'center',
    // justifyContent: 'space-between',
    // alignContent: 'center',
    // padding: 16,
    paddingTop:60,
   
  },

   notLoginScreenHeader:{
    fontFamily: 'MonumentExtended-Regular',
    fontSize: 24,
    color: 'white',
    fontWeight: '400',
    fontStyle: 'normal',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    width:'100%',
    textAlign:'center',
    padding:16,
  },

  //SignUp
  //   teamsandConditionText: {
  //     color: '#FFFFFF7A',
  //     fontFamily: 'Urbanist-SemiBold',
  //     fontSize: 14,
  //     marginLeft: 5,
  //     fontWeight: '600',
  //     textDecorationLine: 'underline',
  //     textDecorationStyle: 'solid',
  //     opacity: 2,
  //     textShadowColor: 'rgba(255,255,255,0.6)',
  //     textShadowOffset: { width: 0, height: 0 },
  //     textShadowRadius: 1,
  //   },
  //   bycountuningAgreementText: {
  //     color: 'rgba(255, 255, 255, 0.48)',
  //     fontFamily: 'Urbanist-Regular',
  //     fontSize: 14,
  //     fontWeight: 400,
  //   },

  //   teamsandConditionContainer: {
  //     flexDirection: 'row',
  //     alignItems: 'center',
  //     justifyContent: 'center',
  //   },

  //   teamandCondition: {
  //     alignItems: 'center',
  //     justifyContent: 'flex-end',
  //     flex: 1,
  //     paddingBottom: 30,
  //   },

  infoContainer: {
    flexDirection: 'row',
    marginTop: 8,
    paddingLeft: 6,
    paddingRight: 6,
  },
  errorText: {
    color: 'red',
    fontSize: 12,
    marginTop: 4,
  },
 infoText: {
    color: '#FFFFFF7A',
    fontFamily: 'Urbanist-Medium',
    fontSize: 14,
    lineHeight: 20,
  },
   infoText1: {
    color: '#fff',
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 14,
    lineHeight: 20,
    fontWeight:500,
  },

  stepCircle: {
    width: 12,
    height: 12,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },

  activeStepCircle: {
    backgroundColor: '#FFFFFF',
    width: 12,
    height: 12,
    flexShrink: 0,
    borderColor: '#ffffff4e',
    alignItems: 'center',
    borderRadius: 40,
    justifyContent: 'center',
    boxShadow: '0 0.833px 3.333px 0 rgba(0, 0, 0, 0.25);',
    shadowColor: '0 0.833px 3.333px rgba(0, 0, 0, 0.25)',
  },
  //   eyeCross: {
  //     width: 19,
  //     height: 15,
  //   },

  stepIndicatorContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    gap: 6,
  },

  inactiveStepCircle: {
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    width: 12,
    height: 12,
    flexShrink: 0,
    borderColor: '#ffffff4e',
    alignItems: 'center',
    borderRadius: 40,
    justifyContent: 'center',
    boxShadow: '0 0.833px 3.333px 0 rgba(0, 0, 0, 0.25);',
    shadowColor: '0 0.833px 3.333px rgba(0, 0, 0, 0.25)',
  },

  //   flex_1: {
  //     flex: 1,
  //     padding: 1,
  //     alignItems: 'center',
  //   },
  //   eyeIcon: {
  //     width: 19,
  //     height: 15,
  //     // paddingRight: 16,
  //   },

  unizyTitle: {
    fontFamily: 'Monument Extended',
    textAlign: 'center',
    fontSize: 25,
    fontWeight: '400',
    marginTop: 40,
    padding: 16,
    color: '#FFFFFF',
  },
  //   loginButton: {
  //     display: 'flex',
  //     width: '100%',
  //     height: 48,
  //     justifyContent: 'center',
  //     alignItems: 'center',
  //     gap: 4,
  //     borderRadius: 100,
  //     paddingTop: 6,
  //     paddingBottom: 6,
  //     backgroundColor: 'rgba(255, 255, 255, 0.56)',
  //     marginTop: 16,
  //     borderWidth: 0.5,
  //     borderColor: '#ffffff2c',
  //   },
  //   loginText: {
  //     color: '#002050',
  //     textAlign: 'center',
  //     fontFamily: 'Urbanist-Medium',
  //     fontSize: 17,
  //     fontWeight: 500,
  //     lineHeight: 22,
  //     letterSpacing: 1,
  //   },
  resetPasswordformContainer: {
    width: '90%',
    padding: 20,
    borderRadius: 24,
    alignItems: 'center',
    gap: 10,
    flexDirection: 'column',
    borderWidth: 0.2,
    borderColor: '#ffffff3d',
    backgroundColor:
      'radial-gradient(189.13% 141.42% at 0% 0%, rgba(255, 255, 255, 0.06) 0%, rgba(255, 255, 255, 0.10) 50%, rgba(0, 0, 0, 0.10) 100%)',
    boxShadow: 'rgba(255, 255, 255, 0.12) inset -1px 0px 5px 1px',
    overflow: 'hidden',
  },
  formContainer: {
    width: '90%',
    padding: 16,
    gap: 10,
    marginTop: -15,
    flexDirection: 'column',
    alignItems: 'center',
    borderWidth: 0.2,
    borderColor: '#ffffff3d',
    borderRadius: 16,
    backgroundColor:
      'radial-gradient(189.13% 141.42% at 0% 0%, rgba(255, 255, 255, 0.06) 0%, rgba(255, 255, 255, 0.10) 50%, rgba(0, 0, 0, 0.10) 100%)',
    boxShadow: 'rgba(255, 255, 255, 0.12) inset -1px 0px 5px 1px',
  },

  nameRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingBottom: 10,
  },

  signupPrompt: {
    color: 'rgba(255, 255, 255, 0.48)',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    fontWeight: '400',
  },
  signupPrompt1: {
    color: 'rgba(255, 255, 255, 0.48)',
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 14,
    fontWeight: '600',
    opacity: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },

  termsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },

  login_container1: {
    display: 'flex',
    width: '49%',
    height: 40,
    gap: 10,
    alignSelf: 'stretch',
    borderRadius: 12,
    borderWidth: 0.6,
    borderColor: '#ffffff2c',
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 1.761px 6.897px 0 rgba(0, 0, 0, 0.25)',
  },

  personalEmailID_TextInput1: {
    width: '85.5%',
    fontFamily: 'Urbanist-Regular',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 22,
    fontStyle: 'normal',
    color: '#fff',
    // paddingLeft: 2,
  },

  search_container: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    borderRadius: 50,
    boxShadow: '0 2px 8px 0 rgba(0, 0, 0, 0.25)',
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
  },
  searchIcon: {
    padding: 5,
    margin: 10,
    height: 24,
    width: 24,
  },
  searchBar: {
    fontFamily: 'Urbanist-Medium',
    marginLeft: -5,
    fontWeight: 500,
    fontSize: 17,
  },

  listContainer: {
    justifyContent: 'center',
    alignItems: 'flex-start',
    alignSelf: 'stretch',
    borderRadius: 12,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 1.761px 6.897px 0 rgba(0, 0, 0, 0.25)',
    // maxHeight: '80%',
  },
  listContent: {
    paddingLeft: 10,
    paddingRight: 10,
  },
  flatListStyle: {
    width: '98%',
    alignSelf: 'center',
  },
  languageItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomColor: '#ffffff23',
    borderBottomWidth: 1,
  },
  languageInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
    flex: 2,
  },
  flag: {
    marginRight: 12,
    resizeMode: 'cover',
    borderRadius: 2,
    width: 34,
    height: 24,
  },
  languageText: {
    color: 'white',
    fontSize: 17,
    fontFamily: 'Urbanist-Medium',
    fontWeight: '500',
    mixBlendMode: 'normal',
  },
  radioButton_round: {
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    width: 15,
    height: 15,
    flexShrink: 0,
    borderColor: '#ffffff4e',

    alignItems: 'center',
    borderRadius: 50,
    justifyContent: 'center',
    boxShadow: '0 0.833px 3.333px 0 rgba(0, 0, 0, 0.25);',
    shadowColor: '0 0.833px 3.333px rgba(0, 0, 0, 0.25',
  },
  radioButton: {
    width: 8,
    height: 8,
    borderRadius: 10,
    // borderWidth: 1,
    // borderColor: '#ffffff4e',
    // boxShadow: '0 0.833px 3.333px 0 rgba(0, 0, 0, 0.25);',
    // backgroundColor:
    //   'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
  },
  radioButtonSelected: {
    // borderColor: 'white',
    backgroundColor: 'white',

    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ffffff4e',
    boxShadow: '0 0.833px 3.333px 0 rgba(0, 0, 0, 0.25);',
    // backgroundColor:
    //   'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
  },

  blurstyle: {
    backgroundColor: 'transparent',
  },
  
  resetTitle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.02 * 17,
    textAlign: 'center',
    color: '#FFF',
    fontWeight: 600,
  },

  privacyContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: 6,
  },

  termsText: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 10,
  },

  termsText1: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 10,
    marginBottom: 12,
  },
  goBackText: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-SemiBold',
    fontWeight: '600',
    fontSize: 14,
    marginVertical: 6,
    textAlign: 'center',
    lineHeight: 19.6,
    letterSpacing: 0,
    opacity: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },

  overlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    // opacity: 0.4
  },

  popupContainer: {
    // width: width * 0.85,
    padding: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    overflow: 'hidden',

    backgroundColor: 'rgba(253, 253, 253, 0.07)',
    boxShadow:
      'rgba(255, 2550, 255, 0.1) inset -0.90px 0px 1px 0px,',
  },

  logo: {
    width: 64,
    height: 64,
    marginBottom: 20,
  },


  resetPasswordoverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  ResetPasswordpopupContainer: {
    // width: width * 0.85,
    padding: 20,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    overflow: 'hidden',

    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  resetPasswordlogo: {
    width: 64,
    height: 64,
    marginBottom: 20,
  },
  resetPasswordloginButton: {
    display: 'flex',
    width: '100%',
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
    borderRadius: 100,
    paddingTop: 6,
    paddingBottom: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.56)',
    marginTop: 16,
    borderWidth: 0.5,
    borderColor: '#ffffff2c',
  },
  resetPasswordloginText: {
    color: '#002050',
    textAlign: 'center',
    fontFamily: 'Urbanist-Medium',
    fontSize: 17,
    fontWeight: 500,
    letterSpacing: 1,
    width: '100%',
  },
  resetPasswordtermsText1: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 10,
    marginBottom: 12,
  },

  signUpfullScreenContainer: {
    display: 'flex',
    paddingRight: 20,
    paddingLeft: 16,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    flexShrink: 0,
    flexDirection: 'row',
    paddingTop: 20,
  },

  signunizyText: {
    color: '#FFFFFF',
    fontFamily: 'MonumentExtended-Regular',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 120,
    textAlign: 'center',
    flex: 1,
    gap: 10,
    paddingLeft: 24,
  },
  signupemptyView: {
    display: 'flex',
    padding: 12,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    borderRadius: 40,
    opacity: 0.01,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 2px 8px 0 rgba(0, 0, 0, 0.25)',
  },

  signupcardView: {
    height: 600,
    paddingTop: 15,
    padding: 10,
    marginTop: -15,
    width: '90%',
    borderWidth: 0.2,
    gap: 3,
    borderColor: '#ffffff3d',
    borderRadius: 16,
    backgroundColor:
      'radial-gradient(189.13% 141.42% at 0% 0%, rgba(255, 255, 255, 0.06) 0%, rgba(255, 255, 255, 0.10) 50%, rgba(0, 0, 0, 0.10) 100%)',
    boxShadow: '0 2px 8px 0 rgba(0, 0, 0, 0.09)',
    overflow: 'hidden',
  },
  ///dummy

  dumcontainer: {
    flex: 1,
    backgroundColor: '#ffffffff',
    justifyContent: 'flex-end',
  },
  animatedContainer: {
    width: '100%',
    overflow: 'hidden', // important for sliding
    backgroundColor: 'transparent',
  },
  box1: {
    backgroundColor: 'skyblue',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 50, // this makes height dynamic
  },
  box2: {
    backgroundColor: 'tomato',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 100, // this makes it taller than first
  },
  text: {
    fontSize: 20,
    color: '#fff',
  },
  button: {
    marginTop: 20,
    padding: 10,
    backgroundColor: '#333',
    color: '#fff',
    borderRadius: 10,
  },
  btn: {
    width: 120,
    height: 40,
    backgroundColor: '#333',
    borderRadius: 10,
  },
  //SendOtpScreen
  sendOtpflex_1: {
    flex: 1,
    alignItems: 'center',
  },

  sendOtpstepCircle: {
    width: 12,
    height: 12,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },

  sendOtpactiveStepCircle: {
    backgroundColor: '#FFFFFF',
    width: 12,
    height: 12,
    flexShrink: 0,
    borderColor: '#ffffff4e',
    alignItems: 'center',
    borderRadius: 40,
    justifyContent: 'center',
    boxShadow: '0 0.833px 3.333px 0 rgba(0, 0, 0, 0.25);',
    shadowColor: '0 0.833px 3.333px rgba(0, 0, 0, 0.25)',
  },

  endOtpstepIndicatorContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    gap: 6,
  },

  sendOtpinactiveStepCircle: {
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    width: 12,
    height: 12,
    flexShrink: 0,
    borderColor: '#ffffff4e',
    alignItems: 'center',
    borderRadius: 40,
    justifyContent: 'center',
    boxShadow: '0 0.833px 3.333px 0 rgba(0, 0, 0, 0.25);',
    shadowColor: '0 0.833px 3.333px rgba(0, 0, 0, 0.25)',
  },

  sendOtpotpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '70%',
    alignSelf: 'center',
    gap: 6, // works in RN 0.71+, otherwise use marginRight
    marginTop: 16,
  },

  sendOtpotpBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    paddingTop: 8,
    paddingRight: 12,
    paddingBottom: 8,
    paddingLeft: 12,
    textAlign: 'center',
    fontSize: 18,
    color: '#fff',
    fontWeight: '600',
    borderWidth: 1,
    borderColor: '#ffffff2c',
    elevation: 0,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: 'rgba(255, 255, 255, 0.02)inset -1px 0px 15px 1px',
  },

  sendOtpformContainer: {
    width: '90%',
    padding: 20,
    borderRadius: 24,
    alignItems: 'center',
    gap: 10,
    marginTop: -15,
    flexDirection: 'column',
    borderWidth: 0.2,
    borderColor: '#ffffff3d',
    backgroundColor:
      'radial-gradient(189.13% 141.42% at 0% 0%, rgba(255, 255, 255, 0.06) 0%, rgba(255, 255, 255, 0.10) 50%, rgba(0, 0, 0, 0.10) 100%)',
    boxShadow: 'rgba(255, 255, 255, 0.12) inset -1px 0px 5px 1px',
    overflow: 'hidden',
  },

  sendOtpresetTitle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.02 * 17,
    textAlign: 'center',
    color: '#FFF',
    fontWeight: 600,
  },

  sendOtpprivacyContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: 16,
  },

  sendOtptermsText: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 10,
  },

  sendOtptermsText1: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 10,
    marginBottom: 12,
  },

  sendOtplogin_container: {
    display: 'flex',
    width: '100%',
    height: 40,
    gap: 10,
    alignSelf: 'stretch',
    borderRadius: 12,
    borderWidth: 0.6,
    borderColor: '#ffffff2c',
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 1.761px 6.897px 0 rgba(0, 0, 0, 0.25)',
  },
  sendOtppersonalEmailID_TextInput: {
    width: '93%',
    fontFamily: 'Urbanist-Regular',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 22,
    fontStyle: 'normal',
  },

  sendOtploginButton: {
    display: 'flex',
    width: '100%',
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
    borderRadius: 100,
    paddingTop: 6,
    paddingBottom: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.56)',
    marginTop: 16,
    borderWidth: 0.5,
    borderColor: '#ffffff2c',
  },
  sendOtploginText: {
    color: '#002050',
    textAlign: 'center',
    fontFamily: 'Urbanist-Medium',
    fontSize: 17,
    fontWeight: 500,
    letterSpacing: 1,
    width: '100%',
  },

  sendOtploginButton1: {
    width: '100%',
    marginBottom: 4, // Increased space below button
  },

  sendOtpresendText: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-Regular',
    fontWeight: '400',
    fontSize: 14,
    paddingTop: 2,
    textAlign: 'center',
    lineHeight: 19.6,
    letterSpacing: 0,
  },

  sendOtpresendText1: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-SemiBold',
    fontWeight: '600',
    fontSize: 14,
    paddingTop: 2,
    textAlign: 'center',
    lineHeight: 19.6,
    letterSpacing: 0,
    opacity: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },

  sendOtpresendText2: {
    color: '#fff',
    fontFamily: 'Urbanist-SemiBold',
    fontWeight: '600',
    fontSize: 14,
    paddingTop: 2,
    textAlign: 'center',
    lineHeight: 19.6,
    letterSpacing: 0,
    opacity: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },

  sendOtpgoBackText: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-Regular',
    fontWeight: '400',
    fontSize: 14,
    paddingTop: 4,
    textAlign: 'center',
    lineHeight: 19.6,
    letterSpacing: 0,
  },

  sendOtpgoBackText1: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-SemiBold',
    fontWeight: '600',
    fontSize: 14,
    paddingTop: 4,
    textAlign: 'center',
    lineHeight: 19.6,
    letterSpacing: 0,
    opacity: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },

  sendOtpoverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },

  sendOtppopupContainer: {
    // width: width * 0.85,
    padding: 20,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
  },

  sendOtplogo: {
    width: 64,
    height: 64,
    marginBottom: 20,
  },

  sendOtpfullScreenContainer: {
    display: 'flex',
    paddingRight: 20,
    paddingLeft: 16,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    flexShrink: 0,
    flexDirection: 'row',

    paddingTop: 20,
  },
  sendOtpbackIconRow: {
    display: 'flex',
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 40,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 2px 8px 0 rgba(0, 0, 0, 0.25)',
    borderWidth: 0.6,
    borderColor: '#ffffff2c',
  },
  sendOtpunizyText: {
    color: '#FFFFFF',
    fontFamily: 'MonumentExtended-Regular',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 120,
    textAlign: 'center',
    flex: 1,
    gap: 10,
    paddingLeft: 24,
  },
  sendOtpemptyView: {
    display: 'flex',
    padding: 12,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    borderRadius: 40,
    opacity: 0.01,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 2px 8px 0 rgba(0, 0, 0, 0.25)',
  },

  //   VerifyPasswordScreen
  verifyflex_1: {
    flex: 1,
    alignItems: 'center',
  },

  resendText2: {
    color: '#fff',
    fontFamily: 'Urbanist-SemiBold',
    fontWeight: '600',
    fontSize: 14,
    paddingTop: 2,
    textAlign: 'center',
    lineHeight: 19.6,
    letterSpacing: 0,
    opacity: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },

  verifystepCircle: {
    width: 12,
    height: 12,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },

  verifyactiveStepCircle: {
    backgroundColor: '#FFFFFF',
    width: 12,
    height: 12,
    flexShrink: 0,
    borderColor: '#ffffff4e',
    alignItems: 'center',
    borderRadius: 40,
    justifyContent: 'center',
    boxShadow: '0 0.833px 3.333px 0 rgba(0, 0, 0, 0.25);',
    shadowColor: '0 0.833px 3.333px rgba(0, 0, 0, 0.25)',
  },

  verifystepIndicatorContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    gap: 6,
  },

  verifyinactiveStepCircle: {
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    width: 12,
    height: 12,
    flexShrink: 0,
    borderColor: '#ffffff4e',
    alignItems: 'center',
    borderRadius: 40,
    justifyContent: 'center',
    boxShadow: '0 0.833px 3.333px 0 rgba(0, 0, 0, 0.25);',
    shadowColor: '0 0.833px 3.333px rgba(0, 0, 0, 0.25)',
  },

  verifyotpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '70%',
    alignSelf: 'center',
    gap: 8,
    marginTop: 12,
  },

  verifyotpBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    paddingTop: 8,
    paddingRight: 12,
    paddingBottom: 8,
    paddingLeft: 12,
    textAlign: 'center',
    fontSize: 18,
    color: '#fff',
    fontWeight: '600',
    borderWidth: 1,
    borderColor: '#ffffff2c',
    elevation: 0,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: 'rgba(255, 255, 255, 0.02)inset -1px 0px 15px 1px',
  },

  verifyformContainer: {
    width: '90%',
    padding: 20,
    borderRadius: 24,
    alignItems: 'center',
    gap: 10,
    marginTop: -15,
    flexDirection: 'column',
    borderWidth: 0.2,
    borderColor: '#ffffff3d',
    backgroundColor:
      'radial-gradient(189.13% 141.42% at 0% 0%, rgba(255, 255, 255, 0.06) 0%, rgba(255, 255, 255, 0.10) 50%, rgba(0, 0, 0, 0.10) 100%)',
    boxShadow: 'rgba(255, 255, 255, 0.12) inset -1px 0px 5px 1px',
    overflow: 'hidden',
  },

  verifyresetTitle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.02 * 17,
    textAlign: 'center',
    color: '#FFF',
    fontWeight: 600,
  },

  verifyprivacyContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: 16,
  },

  verifytermsText: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 10,
  },

  verifylogin_container: {
    marginTop: 16,
    display: 'flex',
    width: '100%',
    height: 40,
    gap: 10,
    alignSelf: 'stretch',
    borderRadius: 12,
    borderWidth: 0.6,
    borderColor: '#ffffff2c',
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 1.761px 6.897px 0 rgba(0, 0, 0, 0.25)',
  },
  verifypersonalEmailID_TextInput: {
    width: '93%',
    fontFamily: 'Urbanist-Regular',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 22,
    fontStyle: 'normal',
    color: '#fff',
  },

  verifyloginButton: {
    display: 'flex',
    width: '100%',
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
    borderRadius: 100,
    paddingTop: 6,
    paddingBottom: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.56)',
    marginTop: 16,
    borderWidth: 0.5,
    borderColor: '#ffffff2c',
  },
  verifyloginText: {
    color: '#002050',
    textAlign: 'center',
    fontFamily: 'Urbanist-Medium',
    fontSize: 17,
    fontWeight: 500,
    letterSpacing: 1,
    width: '100%',
  },

  verifyloginButton1: {
    display: 'flex',
    width: '100%',
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
    borderRadius: 100,
    paddingTop: 6,
    paddingBottom: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.56)',
    borderWidth: 0.5,
    borderColor: '#ffffff2c',
    marginTop: 16,
  },

  verifyresendText: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-Regular',
    fontWeight: '400',
    fontSize: 14,
    paddingTop: 12,
    textAlign: 'center',
    lineHeight: 19.6,
    letterSpacing: 0,
  },

  verifyresendText1: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-SemiBold',
    fontWeight: '600',
    fontSize: 14,
    paddingTop: 12,
    textAlign: 'center',
    lineHeight: 19.6,
    letterSpacing: 0,
    opacity: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },

  verifygoBackText: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-Regular',
    fontWeight: '400',
    fontSize: 14,
    paddingTop: 12,
    textAlign: 'center',
    lineHeight: 19.6,
    letterSpacing: 0,
  },

  verifygoBackText1: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-SemiBold',
    fontWeight: '600',
    fontSize: 14,
    paddingTop: 12,
    textAlign: 'center',
    lineHeight: 19.6,
    letterSpacing: 0,
    opacity: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },

  verifyfullScreenContainer: {
    display: 'flex',
    paddingRight: 20,
    paddingLeft: 16,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    flexShrink: 0,
    flexDirection: 'row',

    paddingTop: 20,
  },
  verifybackIconRow: {
    display: 'flex',
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 40,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 2px 8px 0 rgba(0, 0, 0, 0.25)',
    borderWidth: 0.6,
    borderColor: '#ffffff2c',
  },
  verifyunizyText: {
    color: '#FFFFFF',
    fontFamily: 'MonumentExtended-Regular',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 120,
    textAlign: 'center',
    flex: 1,
    gap: 10,
    paddingLeft: 24,
  },
  verifyemptyView: {
    display: 'flex',
    padding: 12,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    borderRadius: 40,
    opacity: 0.01,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 2px 8px 0 rgba(0, 0, 0, 0.25)',
  },

  //  ProfileScreen

  profilesignupPrompt: {
    color: 'rgba(255, 255, 255, 0.48)',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    fontWeight: '400',
  },
  profilesignupPrompt1: {
    color: 'rgba(255, 255, 255, 0.48)',
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 14,
    fontWeight: '600',
    opacity: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },

  profileoverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.57)',
    // opacity: (Platform.OS === 'ios' ? 0.9: 1) 
  },

  profilelogo1: {
    width: 64,
    height: 64,
    marginBottom: 20,
  },

  profilepopupContainer: {
    // width: width * 0.85,
    padding: 20,
    borderRadius: 24,
    // backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    // filter: 'blur(2px)',
    
    backgroundColor: 'rgba(253, 253, 253, 0.07)',
    boxShadow:
      'rgba(255, 2550, 255, 0.1) inset -0.90px 0px 1px 0px,',
  },
  profiletermsText1: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 10,
    marginBottom: 12,
    opacity: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },
  profiletermsText2: {
    color: '#fff',
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 17,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 10,
    marginBottom: 12,
    fontWeight: 600,
  },

  profilebigCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    boxShadow: 'rgba(255, 255, 255, 0.02)inset -1px 0px 15px 1px',
    borderWidth: 1,
    borderColor: '#ffffff2c',
  },
  profilecameraButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profilecameraIcon: {
    width: 40,
    height: 40,
    marginLeft: 5,
    marginTop: 5,
  },

  profileavatarContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },

  profilelogo: {
    width: 120,
    height: 120,
    borderRadius: 60,
  },

  profileflex_1: {
    flex: 1,
    alignItems: 'center',
  },

  profilestepCircle: {
    width: 12,
    height: 12,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },

  profileactiveStepCircle: {
    backgroundColor: '#FFFFFF',
    width: 12,
    height: 12,
    flexShrink: 0,
    borderColor: '#ffffff4e',
    alignItems: 'center',
    borderRadius: 40,
    justifyContent: 'center',
    boxShadow: '0 0.833px 3.333px 0 rgba(0, 0, 0, 0.25);',
    shadowColor: '0 0.833px 3.333px rgba(0, 0, 0, 0.25)',
  },

  profilestepIndicatorContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    gap: 6,
  },

  profileinactiveStepCircle: {
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    width: 12,
    height: 12,
    flexShrink: 0,
    borderColor: '#ffffff4e',
    alignItems: 'center',
    borderRadius: 40,
    justifyContent: 'center',
    boxShadow: '0 0.833px 3.333px 0 rgba(0, 0, 0, 0.25);',
    shadowColor: '0 0.833px 3.333px rgba(0, 0, 0, 0.25)',
  },

  profileformContainer: {
    width: '90%',
    padding: 20,
    borderRadius: 24,
    alignItems: 'center',
    gap: 10,
    marginTop: -15,
    flexDirection: 'column',
    borderWidth: 0.2,
    borderColor: '#ffffff3d',
    backgroundColor:
      'radial-gradient(189.13% 141.42% at 0% 0%, rgba(255, 255, 255, 0.06) 0%, rgba(255, 255, 255, 0.10) 50%, rgba(0, 0, 0, 0.10) 100%)',
    boxShadow: 'rgba(255, 255, 255, 0.12) inset -1px 0px 5px 1px',
    overflow: 'hidden',
  },

  profileprofileresetTitle: {
    fontFamily: 'Urbanist-SemiBold',
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.02 * 17,
    textAlign: 'center',
    color: '#FFF',
    fontWeight: 600,
  },

  profileprivacyContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: 16,
  },

  profiletermsText: {
    color: 'rgba(255,255,255,0.48)',
    fontFamily: 'Urbanist-Regular',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 10,
    opacity: 2,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },

  profileloginButton: {
    display: 'flex',
    width: '100%',
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
    borderRadius: 100,
    paddingTop: 6,
    paddingBottom: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.56)',
    marginTop: 16,

    borderWidth: 0.5,
    borderColor: '#ffffff2c',
  },
  profileloginText: {
    color: '#002050',
    textAlign: 'center',
    fontFamily: 'Urbanist-Medium',
    fontSize: 17,
    fontWeight: 500,
    letterSpacing: 1,
    width: '100%',
  },

  profilefullScreenContainer: {
    display: 'flex',
    paddingRight: 20,
    paddingLeft: 16,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    flexShrink: 0,
    flexDirection: 'row',

    paddingTop: 20,
  },
  profilebackIconRow: {
    display: 'flex',
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 40,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 2px 8px 0 rgba(0, 0, 0, 0.25)',
    borderWidth: 0.6,
    borderColor: '#ffffff2c',
  },
  profileunizyText: {
    color: '#FFFFFF',
    fontFamily: 'MonumentExtended-Regular',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 120,
    textAlign: 'center',
    flex: 1,
    gap: 10,
    paddingLeft: 24,
  },
  profileemptyView: {
    display: 'flex',
    padding: 12,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    borderRadius: 40,
    opacity: 0.01,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 2px 8px 0 rgba(0, 0, 0, 0.25)',
  },

  mainTemsAndConditions: {
    position: 'absolute',
    bottom: (Platform.OS === 'ios' ? 30 : 20), // adjust spacing
    left: 0,
    right: 0,
    alignItems: 'center',
  },
});