# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command(
  'node',
  ['-p',
   'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      { paths: [process.argv[1]] }
    )',
   __dir__]
).strip

require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'unizy' do
  config = use_native_modules!
  # pod 'notifee_react-native', :path => '../node_modules/@notifee/react-native'
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false
  )

  setup_permissions([
    'LocationWhenInUse',
    'LocationAlways',
    'Camera',
    'PhotoLibrary',
    'PhotoLibraryAddOnly'
  ])

  # Firebase core
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseMessaging', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true

  # Firebase features
  pod 'Firebase/Crashlytics', :modular_headers => true
  pod 'Firebase/Analytics', :modular_headers => true

  # Required Swift dependencies
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'nanopb', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # 🔥 REQUIRED FIX FOR Reanimated 4 + RNWorklets
    installer.pods_project.targets.each do |target|
      if target.name == 'RNReanimated'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        end
      end
    end

    # 🔥 fmt FIX (ONLY for fmt, not global)
    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |config|

          # ✅ Force C++17 ONLY for fmt
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++17'

          # ✅ Disable constexpr issues
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_USE_CONSTEXPR=0'

          # ✅ Extra safety
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(inherited)']
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-DFMT_HEADER_ONLY=1'
        end
      end
    end

  end
end