export const Constant = {
  REQUIRED_ALL_FIELDS: 'Please fill all required fields',
  VALID_EMAI_LADDRESS: 'Please enter a valid email address',
  PASSWORD_RESET_LINK_SENT: 'Password reset link sent',
  SOMTHING_WENT_WRONG: 'Something went wrong.Please try again',
  NETWORK_ERROR_PLEASE_TRY_AGAIN: 'Network error, please try again',
  INVALID_SERVER_RESPONSE: 'Invalid server response',
  INVALID_EMAIL_OR_PASSWORD: 'Invalid Email or Password',
  LOGIN_SUCCESSFUL: 'User logged in successfully',
  INVALID_USER_DATA_RECEIVED: 'Invalid user data received',
  PASSWORD_MUST_BE_AT_LEAST_8_CHARACTERS:'Password must be at least 8 characters long.',
  PASSWORDS_DO_NOT_MATCH: 'Passwords do not match.',
  PASSWORD_VALID:'Min 8 chars: upper, lower, number, symbol.',
  FAIL_TO_SEND_OTP: 'Failed to send OTP',
  PLEASE_ENTER_ALL_4_DIGITS_OF_THE_OTP: 'Please enter all 4 digits of the OTP',
  OTP_ID_MISSING:"OTP ID missing. Please request new OTP.",
  OPT_VERIFICATION_FAILED:'OTP verification failed',
  ALERT_MESSAGE_PLEASE_SELECT_AN_IMAGE_FIRST:'Please select an image first',
  PAYMENT_COMPLETE:'Payment completed successfully!',
  PAYMENT_FAIL:'Payment failed: Please try again.',
  NO_RESULT_FOUND:'No results found',
  UNABLE_TO_LOGIN:'Please login to continue',
  INVALID_ACCOUNT_LINK:'Account link URL not found in response',
  ENTER_RATING:'Please select a rating',
  ENTER_REVIEW:'Please enter your comment',
  USER_NOT_AUTH:'User authentication is missing.',
  NEW_VALID_PASSWORD:'New password must be different from current password.',
  DATA_NOT_SAVE:'Failed to save form data',
  DATA_UPLOAD:'All data uploaded successfully',
  IMAGE_DELETE:'Image deleted successfully',
  IMAGE_UPLOAD:'Image uploaded successfully',
  VERIFY_PERSONAL_MAIL:'Please verify your personal email Id',
  VERIFY_STUDENT_MAIL:'Please verify your student email Id',
  IS_MAN:"is mandatory",
  ARE_MAN:'are mandatory',
  MAXIMUM:"Maximum",
  IMAGE_ALLOWED:"images allowed",
  USER_LOGOUT:'User Logout Successfully',
  LOGOUT_FAIL:'Logout failed! Please try again.',
  PURCHASE_SUCCESS:'Purchased successfully!',


  // PUBLIC_KEY:'pk_test_51SIt8yJfHNIMSZxgncWbKpvnGsppBiwxAA3Fk3XleikVjZiMPyTt5lCOAUQCwrbv0HX1fDgJsmHYkfJPRK8kRSOF00JGovG410'
  PUBLIC_KEY:'pk_test_51SIt9CJDRdvrnoGE1i7V1uIAllKH7k2IcrfgNVUJogzXaJRRDoFDHOdRUThOxxLmK0EX8iGOCx7aBcXkWJ1UwsVJ00wqAJWmKy'
};