export const Constant = {
  
  REQUIRED_ALL_FIELDS: 'REQUIRED_ALL_FIELDS',
  VALID_EMAI_LADDRESS: 'VALID_EMAI_LADDRESS',
  PASSWORD_RESET_LINK_SENT: 'PASSWORD_RESET_LINK_SENT',
  SOMTHING_WENT_WRONG: 'SOMTHING_WENT_WRONG',
  NETWORK_ERROR_PLEASE_TRY_AGAIN: 'NETWORK_ERROR_PLEASE_TRY_AGAIN',
  INVALID_SERVER_RESPONSE: 'INVALID_SERVER_RESPONSE',
  INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  INVALID_USER_DATA_RECEIVED: 'INVALID_USER_DATA_RECEIVED',
  PASSWORD_MUST_BE_AT_LEAST_8_CHARACTERS: 'PASSWORD_MUST_BE_AT_LEAST_8_CHARACTERS',
  PASSWORDS_DO_NOT_MATCH: 'PASSWORDS_DO_NOT_MATCH',
  PASSWORD_VALID: 'PASSWORD_VALID',
  FAIL_TO_SEND_OTP: 'FAIL_TO_SEND_OTP',
  PLEASE_ENTER_ALL_4_DIGITS_OF_THE_OTP: 'PLEASE_ENTER_ALL_4_DIGITS_OF_THE_OTP',
  OTP_ID_MISSING: 'OTP_ID_MISSING',
  OPT_VERIFICATION_FAILED: 'OPT_VERIFICATION_FAILED',
  ALERT_MESSAGE_PLEASE_SELECT_AN_IMAGE_FIRST: 'ALERT_MESSAGE_PLEASE_SELECT_AN_IMAGE_FIRST',
  PAYMENT_COMPLETE: 'PAYMENT_COMPLETE',
  PAYMENT_FAIL: 'PAYMENT_FAIL',
  NO_RESULT_FOUND: 'NO_RESULT_FOUND',
  UNABLE_TO_LOGIN: 'UNABLE_TO_LOGIN',
  INVALID_ACCOUNT_LINK: 'INVALID_ACCOUNT_LINK',
  ENTER_RATING: 'ENTER_RATING',
  ENTER_REVIEW: 'ENTER_REVIEW',
  USER_NOT_AUTH: 'USER_NOT_AUTH',
  NEW_VALID_PASSWORD: 'NEW_VALID_PASSWORD',
  DATA_NOT_SAVE: 'DATA_NOT_SAVE',
  DATA_UPLOAD: 'DATA_UPLOAD',
  IMAGE_DELETE: 'IMAGE_DELETE',
  IMAGE_UPLOAD: 'IMAGE_UPLOAD',
  VERIFY_PERSONAL_MAIL: 'VERIFY_PERSONAL_MAIL',
  VERIFY_STUDENT_MAIL: 'VERIFY_STUDENT_MAIL',
  IS_MAN: 'IS_MAN',
  ARE_MAN: 'ARE_MAN',
  MAXIMUM: 'MAXIMUM',
  IMAGE_ALLOWED: 'IMAGE_ALLOWED',
  USER_LOGOUT: 'USER_LOGOUT',
  LOGOUT_FAIL: 'LOGOUT_FAIL',
  PURCHASE_SUCCESS: 'PURCHASE_SUCCESS',




  // PUBLIC_KEY:'pk_test_51SIt8yJfHNIMSZxgncWbKpvnGsppBiwxAA3Fk3XleikVjZiMPyTt5lCOAUQCwrbv0HX1fDgJsmHYkfJPRK8kRSOF00JGovG410'
  PUBLIC_KEY:'pk_test_51SIt9CJDRdvrnoGE1i7V1uIAllKH7k2IcrfgNVUJogzXaJRRDoFDHOdRUThOxxLmK0EX8iGOCx7aBcXkWJ1UwsVJ00wqAJWmKy'
};