import { StyleSheet } from 'react-native';

export const loginStyles = StyleSheet.create({
  flex_1: {
    flex: 1,
    padding: 1,
    alignItems: 'center',
  },
  fullScreenContainer: {
    display: 'flex',
    paddingRight: 20,
    paddingLeft: 16,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    flexShrink: 0,
    flexDirection: 'row',
  },
  backIconRow: {
    display: 'flex',
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 40,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 2px 8px 0 rgba(0, 0, 0, 0.25)',


     // Outer Shadow (bottom-right)
    shadowColor: "#000",
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 10,
opacity: 0.5,
    // Inner Highlight (top-left light)
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",


},
  unizyText: {
    color: '#FFFFFF',
    fontFamily: 'MonumentExtended-Regular',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 120,
    textAlign: 'center',
    flex: 1,
    gap: 10,
  },
  emptyView: {
    display: 'flex',
    padding: 12,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    borderRadius: 40,
    opacity: 0.01,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 2px 8px 0 rgba(0, 0, 0, 0.25)',
  },
  container: {
    display: 'flex',
    width: '90%',
    padding: 16,
    flexDirection: 'column',
    alignItems: 'center',
    gap: 16,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    opacity: 0.9,


    
    // Outer Shadow (bottom-right)
    shadowColor: "#000",
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  login_container: {
    display: 'flex',
    width: '100%',
    height: 44,
    gap: 10,
    alignSelf: 'stretch',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 1.761px 6.897px 0 rgba(0, 0, 0, 0.25)',


    // Outer Shadow (bottom-right)
    // shadowColor: "#000",
    // shadowOffset: { width: 6, height: 6 },
    // shadowOpacity: 0.4,
    // shadowRadius: 8,
    // elevation: 10,
    // borderWidth: 1,
    // borderColor: "rgba(255,255,255,0.1)",
    // opacity: 0.5,
  },
  personalEmailID_TextInput: {
    width: '90%',
    fontFamily: 'Urbanist-regular',
    fontWeight: '400',
    lineHeight: 22,
    fontSize: 17,
  },
  password_container: {
    display: 'flex',
    width: '100%',
    height: 44,
    gap: 10,
    alignSelf: 'stretch',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 1.761px 6.897px 0 rgba(0, 0, 0, 0.25)',

     // Outer Shadow (bottom-right)
    // shadowColor: "#000",
    // shadowOffset: { width: 6, height: 6 },
    // shadowOpacity: 0.4,
    // shadowRadius: 8,
    // elevation: 10,
    // borderWidth: 1,
    // borderColor: "rgba(255,255,255,0.1)",
    // opacity: 0.5,


},
  password_TextInput: {
    width: '80%',
    fontFamily: 'Urbanist-regular',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 22,
  },
  forgetPasswordText: {
    color: 'rgba(255, 255, 255, 0.48)',
    fontFamily: 'Urbanist-regular',
    fontSize: 14,
    fontStyle: 'normal',
    lineHeight: 9,
    fontWeight: 400,
    width: '100%',
    textAlign: 'right',
  },
  loginButton: {
    display: 'flex',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
    borderRadius: 100,
    paddingTop: 6,
    paddingBottom: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.56)',
  },
  loginText: {
    color: '#002050',
    textAlign: 'center',
    fontFamily: 'Urbanist-regular',
    fontSize: 17,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 22,
    letterSpacing: 1,
  },
  dontHaveAccountText: {
    color: 'rgba(255, 255, 255, 0.48)',
    textAlign: 'center',
    fontFamily: 'Urbanist-regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 19,
  },
  signupText: {
    color: '#FFFFFF7A',
    fontFamily: 'Urbanist-regular',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 'bold',
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
  },
  teamsandConditionText: {
    color: '#FFFFFF7A',
    fontFamily: 'Urbanist-regular',
    fontSize: 14,
    marginLeft: 5,
    fontStyle: 'normal',
    fontWeight: 'bold',
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
  },
  teamsandConditionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },

  bycountuningAgreementText: {
    color: 'rgba(255, 255, 255, 0.48)',
    fontFamily: 'Urbanist',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 400,
  },

  privacyPolicyText: {
    color: '#FFFFFF7A',
    fontFamily: 'Urbanist-regular',
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 'bold',
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
  },

  editText: {
    display: 'flex',
    width: '100%',
    height: 44,
    padding: 12,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 10,
    alignSelf: 'stretch',
    borderRadius: 12,
    backgroundColor:
      'radial-gradient(109.75% 109.75% at 17.5% 6.25%, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.10) 100%)',
    boxShadow: '0 1.761px 6.897px 0 rgba(0, 0, 0, 0.25)',
    fontSize: 17,
    fontFamily: 'Urbanist-Medium',
    fontWeight: '400',
    lineHeight: 22,
  },
  unizy_Text: {
    fontFamily: 'Monument Extended',
    top: 30,
    fontStyle: 'normal',
    lineHeight: 28.8,
    fontSize: 30,
    color: '#FFFFFF',
    fontWeight: '400',
    width: '100%',
    textAlign: 'center',
  },
});
