 export const emoji = [

 { char: '😀', name: 'Grinning Face' },
  { char: '😁', name: 'Beaming Face With Smiling Eyes' },
  { char: '😂', name: 'Face With Tears of Joy' },
  { char: '🤣', name: 'Rolling on the Floor Laughing' },
  { char: '😃', name: 'Grinning Face With Big Eyes' },
  { char: '😄', name: 'Grinning Face With Smiling Eyes' },
  { char: '😅', name: 'Grinning Face With Sweat' },
  { char: '😆', name: 'Grinning Squinting Face' },
  { char: '😉', name: 'Winking Face' },
  { char: '😊', name: 'Smiling Face With Smiling Eyes' },
  { char: '😋', name: 'Face Savoring Food' },
  { char: '😎', name: 'Smiling Face With Sunglasses' },
  { char: '😍', name: 'Smiling Face With Heart-Eyes' },
  { char: '😘', name: 'Face Blowing a Kiss' },
  { char: '🥰', name: 'Smiling Face With Hearts' },
  { char: '😗', name: 'Kissing Face' },
  { char: '😙', name: 'Kissing Face With Smiling Eyes' },
  { char: '😚', name: 'Kissing Face With Closed Eyes' },
  { char: '🙂', name: 'Slightly Smiling Face' },
  { char: '🤗', name: 'Hugging Face' },
  { char: '🤩', name: 'Star-Struck' },
  { char: '🤔', name: 'Thinking Face' },
  { char: '😐', name: 'Neutral Face' },
  { char: '😑', name: 'Expressionless Face' },
  { char: '😶', name: 'Face Without Mouth' },
  { char: '🙄', name: 'Face With Rolling Eyes' },
  { char: '😏', name: 'Smirking Face' },
  { char: '😣', name: 'Persevering Face' },
  { char: '😥', name: 'Sad but Relieved Face' },
  { char: '😮', name: 'Face With Open Mouth' },
  { char: '🤐', name: 'Zipper-Mouth Face' },
  { char: '😯', name: 'Hushed Face' },
  { char: '😪', name: 'Sleepy Face' },
  { char: '😫', name: 'Tired Face' },
  { char: '🥱', name: 'Yawning Face' },
  { char: '😴', name: 'Sleeping Face' },
  { char: '😌', name: 'Relieved Face' },
  { char: '😛', name: 'Face With Tongue' },
  { char: '😜', name: 'Winking Face With Tongue' },
  { char: '🤪', name: 'Zany Face' },
  { char: '😝', name: 'Squinting Face With Tongue' },
  { char: '🤑', name: 'Money-Mouth Face' },
  { char: '🤠', name: 'Cowboy Hat Face' },
  { char: '😈', name: 'Smiling Face With Horns' },
  { char: '👿', name: 'Angry Face With Horns' },
  { char: '😡', name: 'Pouting Face' },
  { char: '😠', name: 'Angry Face' },
  { char: '😤', name: 'Face With Steam From Nose' },
  { char: '😭', name: 'Loudly Crying Face' },
  { char: '😢', name: 'Crying Face' },
  { char: '😰', name: 'Anxious Face With Sweat' },
  { char: '😱', name: 'Face Screaming in Fear' },
  { char: '😨', name: 'Fearful Face' },
  { char: '😳', name: 'Flushed Face' },
  { char: '🤯', name: 'Exploding Head' },
  { char: '😬', name: 'Grimacing Face' },
  { char: '😓', name: 'Downcast Face With Sweat' },
  { char: '😔', name: 'Pensive Face' },
  { char: '😕', name: 'Confused Face' },
  { char: '🙃', name: 'Upside-Down Face' },
  { char: '😇', name: 'Smiling Face With Halo' },
  { char: '🥲', name: 'Smiling Face With Tear' },
  { char: '🥳', name: 'Partying Face' },
  { char: '🤬', name: 'Face With Symbols on Mouth' },
  { char: '🤮', name: 'Face Vomiting' },
  { char: '🤢', name: 'Nauseated Face' },
  { char: '🥶', name: 'Cold Face' },
  { char: '🥵', name: 'Hot Face' },
  { char: '🤧', name: 'Sneezing Face' },
  { char: '🤒', name: 'Face With Thermometer' },
  { char: '🤕', name: 'Face With Head-Bandage' },
  { char: '😷', name: 'Face With Medical Mask' },
  { char: '🤥', name: 'Lying Face' },
  { char: '🫠', name: 'Melting Face' },
 
  // 👍 Gestures & People
  { char: '👍', name: 'Thumbs Up' },
  { char: '👎', name: 'Thumbs Down' },
  { char: '👏', name: 'Clapping Hands' },
  { char: '🙌', name: 'Raising Hands' },
  { char: '👐', name: 'Open Hands' },
  { char: '🤝', name: 'Handshake' },
  { char: '🙏', name: 'Folded Hands' },
  { char: '✌️', name: 'Victory Hand' },
  { char: '🤞', name: 'Crossed Fingers' },
  { char: '🤟', name: 'Love-You Gesture' },
  { char: '🤘', name: 'Sign of the Horns' },
  { char: '👌', name: 'OK Hand' },
  { char: '🤙', name: 'Call Me Hand' },
  { char: '👋', name: 'Waving Hand' },
  { char: '✋', name: 'Raised Hand' },
  { char: '👊', name: 'Oncoming Fist' },
  { char: '🤛', name: 'Left-Facing Fist' },
  { char: '🤜', name: 'Right-Facing Fist' },
  { char: '🫶', name: 'Heart Hands' },
  { char: '🫵', name: 'Pointing at You' },
 
  // 🔥 Objects & Symbols
  { char: '💡', name: 'Light Bulb' },
  { char: '🎉', name: 'Party Popper' },
  { char: '🔥', name: 'Fire' },
  { char: '⭐', name: 'Star' },
  { char: '🌟', name: 'Glowing Star' },
  { char: '⚡', name: 'High Voltage' },
  { char: '💥', name: 'Collision' },
  { char: '💫', name: 'Dizzy' },
  { char: '💯', name: 'Hundred Points' },
  { char: '💪', name: 'Flexed Biceps' },
  { char: '💬', name: 'Speech Balloon' },
  { char: '🗨️', name: 'Left Speech Bubble' },
  { char: '💭', name: 'Thought Balloon' },
  { char: '❤️', name: 'Red Heart' },
  { char: '🧡', name: 'Orange Heart' },
  { char: '💛', name: 'Yellow Heart' },
  { char: '💚', name: 'Green Heart' },
  { char: '💙', name: 'Blue Heart' },
  { char: '💜', name: 'Purple Heart' },
  { char: '🖤', name: 'Black Heart' },
  { char: '🤍', name: 'White Heart' },
  { char: '🤎', name: 'Brown Heart' },
  { char: '💔', name: 'Broken Heart' },
  { char: '❣️', name: 'Heart Exclamation' },
  { char: '💕', name: 'Two Hearts' },
  { char: '💞', name: 'Revolving Hearts' },
  { char: '💓', name: 'Beating Heart' },
  { char: '💗', name: 'Growing Heart' },
  { char: '💖', name: 'Sparkling Heart' },
  { char: '💘', name: 'Heart With Arrow' },
  { char: '💝', name: 'Heart With Ribbon' },
 
  // 🌍 Nature
  { char: '🌞', name: 'Sun With Face' },
  { char: '🌝', name: 'Full Moon With Face' },
  { char: '🌙', name: 'Crescent Moon' },
  { char: '⭐', name: 'Star' },
  { char: '🌈', name: 'Rainbow' },
  { char: '☁️', name: 'Cloud' },
  { char: '🌧️', name: 'Cloud With Rain' },
  { char: '🌩️', name: 'Cloud With Lightning' },
  { char: '🌪️', name: 'Tornado' },
  { char: '🌊', name: 'Water Wave' },
  { char: '🍀', name: 'Four Leaf Clover' },
  { char: '🌸', name: 'Cherry Blossom' },
  { char: '🌹', name: 'Rose' },
  { char: '🌻', name: 'Sunflower' },
  { char: '🌼', name: 'Blossom' },
  { char: '🌴', name: 'Palm Tree' },
  { char: '🌵', name: 'Cactus' },
  { char: '🌿', name: 'Herb' },
  { char: '🍁', name: 'Maple Leaf' },
  { char: '🍂', name: 'Fallen Leaf' },
  { char: '🍃', name: 'Leaf Fluttering in Wind' },
 
  // 🍔 Food
  { char: '🍏', name: 'Green Apple' },
  { char: '🍎', name: 'Red Apple' },
  { char: '🍌', name: 'Banana' },
  { char: '🍉', name: 'Watermelon' },
  { char: '🍇', name: 'Grapes' },
  { char: '🍓', name: 'Strawberry' },
  { char: '🍒', name: 'Cherries' },
  { char: '🍑', name: 'Peach' },
  { char: '🥭', name: 'Mango' },
  { char: '🍍', name: 'Pineapple' },
  { char: '🥥', name: 'Coconut' },
  { char: '🥦', name: 'Broccoli' },
  { char: '🥕', name: 'Carrot' },
  { char: '🌽', name: 'Corn' },
  { char: '🍔', name: 'Hamburger' },
  { char: '🍕', name: 'Pizza' },
  { char: '🍟', name: 'French Fries' },
  { char: '🍩', name: 'Doughnut' },
  { char: '🍪', name: 'Cookie' },
  { char: '🎂', name: 'Birthday Cake' },
  { char: '🍰', name: 'Shortcake' },
  { char: '🧁', name: 'Cupcake' },
  { char: '🍫', name: 'Chocolate Bar' },
  { char: '🍿', name: 'Popcorn' },
  { char: '🍺', name: 'Beer Mug' },
  { char: '🍻', name: 'Clinking Beer Mugs' },
  { char: '🥂', name: 'Clinking Glasses' },
  { char: '🍷', name: 'Wine Glass' },
  { char: '☕', name: 'Hot Beverage' },
 
  // 🚗 Travel
  { char: '🚗', name: 'Car' },
  { char: '🚕', name: 'Taxi' },
  { char: '🚙', name: 'SUV' },
  { char: '🚌', name: 'Bus' },
  { char: '🚎', name: 'Trolleybus' },
  { char: '🏍️', name: 'Motorcycle' },
  { char: '🚲', name: 'Bicycle' },
  { char: '✈️', name: 'Airplane' },
  { char: '🚀', name: 'Rocket' },
  { char: '🛸', name: 'Flying Saucer' },
  { char: '🚢', name: 'Ship' },
  { char: '⚓', name: 'Anchor' },
  { char: '🚉', name: 'Station' },
  { char: '🗺️', name: 'World Map' },
  { char: '🗽', name: 'Statue of Liberty' },
  { char: '🗻', name: 'Mount Fuji' },
  { char: '🏖️', name: 'Beach With Umbrella' },
 
  // 🏁 Flags & Symbols
  { char: '🏳️', name: 'White Flag' },
  { char: '🏴', name: 'Black Flag' },
  { char: '🏁', name: 'Chequered Flag' },
  { char: '🚩', name: 'Triangular Flag' },
  { char: '🎯', name: 'Direct Hit' },
  { char: '🏆', name: 'Trophy' },
  { char: '🥇', name: '1st Place Medal' },
  { char: '🥈', name: '2nd Place Medal' },
  { char: '🥉', name: '3rd Place Medal' },

];